apiVersion: v1
kind: Pod
metadata:
  name: corona-sign-in

x-env:
  - &pg_user
    name: POSTGRES_USER
    value: corona-sign-in
  - &pg_password
    name: POSTGRES_PASSWORD
    value: pass
  - &pg_database
    name: POSTGRES_DB
    value: corona-sign-in


spec:
  containers:
    - name: corona-sign-in-db
      image: postgres:12
      env:
        - *pg_user
        - *pg_password
        - *pg_database
        - name: PGDATA
          value: /var/lib/postgresql/data
      volumeMounts:
        - name: db
          mountPath: /var/lib/postgresql/data

    - name: corona-sign-in-app
      image: localhost/corona-sign-in
      env:
        - name: CORONA_SIGN_IN_DATABASE_URI
          value: postgresql://corona-sign-in:pass@localhost/corona-sign-in
        - name: CORONA_SIGN_IN_SECRET_KEY
          value: irrelevant
      ports: 
        - containerPort: 8080
          hostPort: 8080
          protocol: tcp
      volumeMounts:
        - name: data
          mountPath: /app

  volumes:
    - name: db
      hostPath:
        path: corona-sign-in-db
        type: Directory
    - name: data
      hostPath:
        path: corona-sign-in-data
        type: Directory