name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: pipenv install --dev

      - name: Test with pytest
        run: pipenv run pytest -v

      - name: Test the built docker image
        run: pipenv run invoke containertests

      - name: Test the docker-compose file
        run: pipenv run pytest -v -s tests_docker-compose
